#! /bin/sh

# Minimal base system for initramfs.

name=base
skip_pkg_check=yes
version=0git
revision=1
deps="base-files nomos mlibc openrc init util-nomos bash coreutils" # Dependencies that the recipe requires before being built (build dependencies)