#! /bin/sh

name=bash
version=5.3
revision=1
tarball_url="https://ftp.gnu.org/gnu/bash/bash-${version}.tar.gz"
tarball_blake2b="82d1b54322bbd1e8c2a93380f1b2888a42a1d7186e504f41cee705a0fdd41463d8f20baa1755051e1396192f8ebd089524767d933a9e0b5fb76f2588601539bb"
imagedeps="build-essential"
hostdeps="gcc pkg-config"
deps="mlibc libgcc libstdc++ ncurses readline libiconv libintl libatomic"

prepare() {
    autotools_recursive_regen
}

configure() {
    ac_cv_func_getcwd=yes \
    ac_cv_func_getcwd_malloc=yes \
    autotools_configure \
        CFLAGS="$TARGET_CFLAGS \
            -DDEFAULT_PATH_VALUE='\"/usr/local/sbin:/usr/local/bin:/usr/bin\"' \
            -DSTANDARD_UTILS_PATH='\"/usr/bin\"' \
            -DSYS_BASHRC='\"/etc/bash.bashrc\"' \
            -DSYS_BASH_LOGOUT='\"/etc/bash.bash_logout\"' \
            -DNON_INTERACTIVE_LOGIN_SHELLS \
        " \
        --with-curses \
        --enable-readline \
        --without-bash-malloc
}

build() {
    make -j ${parallelism}
}

package() {
    make install DESTDIR="${dest_dir}"
    ln -s bash "${dest_dir}${prefix}"/bin/sh
    ln -s bash "${dest_dir}${prefix}"/bin/rbash
    mkdir -p "${dest_dir}"/bin
    ln -s ../usr/bin/bash "${dest_dir}"/bin/sh
    ln -s ../usr/bin/bash "${dest_dir}"/bin/rbash

    mkdir -p "${dest_dir}"/etc
    cp -v "${base_dir}"/build-support/extra-files/bash/bash.bashrc "${dest_dir}"/etc/bash.bashrc
}