#! /bin/sh

# Kernel recipe.

name=nomos
skip_pkg_check=yes
version=0git
revision=1
source_dir="nomos" # Built from an actual directory, as opposed to a source recipe
imagedeps="build-essential nasm"
hostdeps="limine"
allow_network="yes" # Network access needs to be allowed
source_allow_network="yes" # Required for prepare() stage curl.

prepare() {
    curl -Lo src/include/limine.h https://raw.githubusercontent.com/limine-bootloader/limine/refs/heads/v9.x/limine.h
    rm -rf flanterm/
    git clone https://codeberg.org/mintsuki/flanterm
    cd flanterm && git checkout bdecdcb1b7 && cd -
    rm -rf uACPI/
    git clone https://github.com/uACPI/uACPI
    cd uACPI && git checkout 229faec && cd -
}

configure() {
    true
}

build() {
    DEBUG=1 WORK_DIR="$(pwd)" make -C ${source_dir} -j${parallelism}
}

package() {
    DEBUG=1 WORK_DIR="$(pwd)" DEST_DIR="${dest_dir}/" PREFIX="usr/" make -C ${source_dir} install
}

