#! /bin/sh

name=readline
version=8.2
revision=1
tarball_url="https://ftp.gnu.org/gnu/readline/readline-${version}.tar.gz"
tarball_blake2b="7974322b9c092a756a79e537df08e8532f8e0fcb598f77732e28287c33ebec9e9837ed88b43334c310892d56a871b423903f0f564def2fbe700a1004f2ae7b18"
hostdeps="gcc pkg-config"
deps="corelibs ncurses"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --with-curses \
        --enable-multibyte
}

build() {
    make SHLIB_LIBS="-lcursesw -ltinfow" -j ${parallelism}
}

package() {
    make install DESTDIR="${dest_dir}"
}